#!/usr/bin/env python3
"""Document every research/sales dataset (schema, counts, meta keys) into data/research/README.md for module
builders, and write data/research/index.json: a small index the landing page reads instead of opening every file.

index.json shape:
  {generated, files:[{name, folder, title, item_count, bytes, generated, lists?}], totals:{...}}
  - name        file stem (e.g. "pe_landscape"); folder is "research" or "sales"
  - item_count  meta.item_count when present, else the length of items (research) or rows (sales)
  - generated   the file's own meta.generated date (YYYY-MM-DD) when present
  - lists       lengths of extra top-level list keys (e.g. bsp_firm.bpi_opportunities)
Run after any research or sales file changes:  python3 scripts/describe_research.py
"""
import json, os, glob, collections, datetime
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, 'data', 'research')


def load(p):
    with open(p, encoding='utf-8') as f:
        return json.load(f)


def records(j):
    """(items, meta, row_count) for both {meta, items} files and columnar {meta, cols, rows} deed files."""
    if not isinstance(j, dict): return (j if isinstance(j, list) else []), {}, None
    items = j.get('items') or []
    rows = j.get('rows')
    return items, j.get('meta') or {}, (len(rows) if isinstance(rows, list) else None)


def as_int(v):
    try: return int(v)
    except (TypeError, ValueError): return None


out = ["# Research & sales datasets — auto-generated schema reference\n",
       "Generated by `scripts/describe_research.py` (also writes `data/research/index.json`). "
       "Shape: `{meta:{...}, items:[...]}` unless noted; deed files under sales/ are columnar `{meta, format, cols, enums, rows}`. "
       "Load with `ctx.data.research('<name>')` (research/) or `ctx.data.load('sales/<name>')` (sales/).\n"]
index = []
for folder in ['research', 'sales']:
    for p in sorted(glob.glob(os.path.join(ROOT, 'data', folder, '*.json'))):
        name = os.path.basename(p)[:-5]
        if folder == 'research' and name == 'index': continue
        size = os.path.getsize(p)
        try: j = load(p)
        except Exception as e:
            out.append(f"\n## {folder}/{name}\nINVALID JSON: {e}\n"); continue
        items, meta, nrows = records(j)
        count = as_int(meta.get('item_count'))
        if count is None: count = nrows if nrows is not None else len(items)
        gen = str(meta.get('generated') or '')[:10] or None
        title = str(meta.get('title') or meta.get('dataset') or name).strip()
        entry = {'name': name, 'folder': folder, 'title': title, 'item_count': count, 'bytes': size, 'generated': gen}
        lists = {k: len(v) for k, v in (j.items() if isinstance(j, dict) else []) if k not in ('meta', 'items', 'rows', 'cols') and isinstance(v, list)}
        if lists: entry['lists'] = lists
        index.append(entry)

        shown = nrows if nrows is not None else len(items)
        out.append(f"\n## {folder}/{name}  ({shown:,} {'rows' if nrows is not None else 'items'} · {size/1e6:.1f} MB)\n")
        if meta:
            out.append(f"meta keys: {', '.join(meta.keys())}\n")
            for k in ('dataset', 'generated', 'method', 'item_count', 'caveats'):
                if k in meta: out.append(f"- **{k}**: {json.dumps(meta[k], ensure_ascii=False)[:400]}\n")
        extra = [k for k in (j.keys() if isinstance(j, dict) else []) if k not in ('meta', 'items')]
        if extra: out.append(f"extra top-level keys: {', '.join(extra)}\n")
        if nrows is not None and isinstance(j.get('cols'), list):
            out.append("columns: " + ', '.join(f"`{c}`" for c in j['cols']) + "\n")
        if items and isinstance(items[0], dict):
            keys = collections.Counter(); types = {}
            for it in items[:500]:
                for k, v in it.items(): keys[k] += 1; types.setdefault(k, type(v).__name__ if v is not None else 'null')
            out.append("fields: " + ', '.join(f"`{k}`:{types[k]}" for k, _ in keys.most_common()) + "\n")
            out.append("sample: `" + json.dumps(items[0], ensure_ascii=False)[:700].replace('`', "'") + "`\n")
            # enumerate categorical values for small-cardinality string fields
            for k in list(keys)[:40]:
                vals = [it.get(k) for it in items if isinstance(it.get(k), str)]
                c = collections.Counter(vals)
                if 1 < len(c) <= 12 and len(vals) > len(items) * 0.5: out.append(f"- `{k}` values: {dict(c.most_common(12))}\n")

with open(os.path.join(RES, 'README.md'), 'w', encoding='utf-8') as f:
    f.write(''.join(out))

res = [e for e in index if e['folder'] == 'research']; sales = [e for e in index if e['folder'] == 'sales']
gens = sorted(e['generated'] for e in index if e['generated'])
doc = {
    'generated': datetime.date.today().isoformat(),
    'files': index,
    'totals': {
        'research_files': len(res), 'research_items': sum(e['item_count'] or 0 for e in res),
        'sales_files': len(sales), 'sales_rows': sum(e['item_count'] or 0 for e in sales),
        'bytes': sum(e['bytes'] for e in index),
        'data_from': gens[0] if gens else None, 'data_to': gens[-1] if gens else None,
    },
}
with open(os.path.join(RES, 'index.json'), 'w', encoding='utf-8') as f:
    json.dump(doc, f, indent=1, ensure_ascii=False); f.write('\n')
print(f"README.md: {len(index)} files · index.json: {json.dumps(doc['totals'])}")
